# Generated by Django 5.2.3 on 2025-07-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaparqueo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaparqueo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='horaparqueo',
            name='servicio_id',
        ),
        migrations.AddField(
            model_name='horaparqueo',
            name='lugar',
            field=models.TextField(null=True, verbose_name='lugar'),
        ),
        migrations.AddField(
            model_name='horaparqueo',
            name='tiempo',
            field=models.TextField(blank=True, verbose_name='tiempo'),
        ),
    ]
