# Generated by Django 5.2.3 on 2025-06-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.TextField(blank=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.TextField(blank=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.TextField(blank=True, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.TextField(blank=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol_id',
            field=models.TextField(null=True, verbose_name='rol'),
        ),
    ]
