# Generated by Django 5.2.3 on 2025-07-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagofinal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagofinal',
            old_name='debit_expiry_dater',
            new_name='debit_expiry_date',
        ),
    ]
