# Generated by Django 5.2.1 on 2025-06-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.TextField(verbose_name='pago')),
                ('vehiculo_id', models.TextField(verbose_name='vehiculo')),
                ('valor_pagar', models.TextField(verbose_name='valor')),
            ],
        ),
    ]
