# Generated by Django 5.2.3 on 2025-07-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_facturacion_vehiculo_id_facturacion_tiempo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='facturacion',
            name='placa',
            field=models.TextField(blank=True, verbose_name='placa'),
        ),
    ]
