# Generated by Django 5.2.3 on 2025-07-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_facturacion_vehiculo_facturacion_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='facturacion',
            name='valor_pagar',
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='tiempo',
            field=models.TextField(null=True, verbose_name='tiempo'),
        ),
    ]
