# Generated by Django 5.2.3 on 2025-07-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_remove_facturacion_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='metodo_pago',
            field=models.TextField(null=True, verbose_name='metodo_pago'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='tiempo',
            field=models.TextField(blank=True, default=1, verbose_name='tiempo'),
            preserve_default=False,
        ),
    ]
