# Generated by Django 5.2.3 on 2025-06-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_rol_vehiculo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='vehiculo_id',
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.TextField(null=True, verbose_name='nombre'),
        ),
    ]
