# Generated by Django 5.2.3 on 2025-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='placa',
            new_name='Placa',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='Cedula',
            field=models.TextField(default=1, verbose_name='cedula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='Nombre',
            field=models.TextField(default=1, verbose_name='nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='Numero',
            field=models.TextField(default=1, verbose_name='numero'),
            preserve_default=False,
        ),
    ]
