# Generated by Django 5.2.3 on 2025-06-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_rename_placa_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='Cedula',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='Placa',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='servicio_id',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cedula',
            field=models.TextField(blank=True, verbose_name='cedula'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nombre',
            field=models.TextField(blank=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero',
            field=models.TextField(blank=True, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placa',
            field=models.TextField(null=True, verbose_name='placa'),
        ),
    ]
