# Generated by Django 5.2.3 on 2025-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pagofinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.TextField(blank=True, verbose_name='card_number')),
                ('card_name', models.TextField(blank=True, verbose_name='card_name')),
                ('expiry_date', models.TextField(blank=True, verbose_name='expiry_date')),
                ('cvv', models.TextField(blank=True, verbose_name='cvv')),
                ('debit_card_number', models.TextField(blank=True, verbose_name='debit_card_number')),
                ('debit_card_name', models.TextField(blank=True, verbose_name='debit_card_name')),
                ('debit_expiry_dater', models.TextField(blank=True, verbose_name='debit_expiry_date')),
                ('debit_cvv', models.TextField(null=True, verbose_name='debit_cvv')),
            ],
        ),
    ]
